DROP TABLE IF EXISTS FUNKOS;
CREATE TABLE IF NOT EXISTS FUNKOS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    cod TEXT NOT NULL,
    nombre VARCHAR(255),
    modelo TEXT CHECK ( modelo IN ('MARVEL', 'DISNEY', 'ANIME', 'OTROS') ),
    precio DOUBLE,
    fecha_lanzamiento VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);